apiVersion: 1
registries:
  GitLab:
    domain: registry.gitlab.com/
    configData: "{{filedata(~/.docker/config.json)}}"
  Local:
    domain: ""
iios:
  app:
    version: "{{packageJSON.version}}"
    # use private registry if necessary (prod deploy)
    # registry: "{{$.registries.GitLab}}"
    registry: "{{$.registries.Local}}"
    imagePullPolicy: IfNotPresent
    replicas: 1
  services:
    dlake:
      version: 3.1.0
      replicas: 1
      ports:
        - containerPort: 20194
          name: dt-service
        - containerPort: 20195
          name: dt1
        - containerPort: 20196
          name: dt2
        - containerPort: 20197
          name: dt3
        - containerPort: 20198
          name: dt4
        - containerPort: 20199
          name: dt5
    auth:
      version: 1.1.0
      replicas: 1
      ports:
        - containerPort: 20295
cluster:
  domain: mini.kube
  letsEncrypt: false
  secrets:
    # you must provide this file
    - name: app-secrets
      file: ~/data/app-secrets.yaml
  ingress: nginx
  kubeConfigPath: ~/.kube/config
