apiVersion: batch/v1
kind: Job
metadata:
  name: iioat-populate
spec:
  template:
    spec:
      containers:
        - name: iioat-populate
          image: ignitial/iioat:IIOS_APP_VERSION
          command: ["npm"]
          args: ["run", "prod:config:populate"]
          imagePullPolicy: Never
          env:
            - name: POPULATE_ALL
              value: "true"
            - name: IIOS_NAMESPACE
              value: "iioat"
            - name: IIOS_REDIS_HOST
              value: "redis.default.svc.cluster.local"
            - name: IIOS_REDIS_PORT
              value: "6379"
            - name: IIOS_MONGODB_URI
              value: "iiomc1-hvphm.gcp.mongodb.net"
            - name: IIOS_MONGODB_USER
              value: "ignitial"
            - name: IIOS_MONGODB_OPTIONS
              value: "retryWrites=true"
            - name: IIOS_DBNAME
              value: "iioat"
            - name: IIOS_MONGODB_CONN_MAX_ATTEMPTS
              value: "60"
            - name: IIOS_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iiosecrets
                  key: mongodb_pwd
      restartPolicy: Never
