apiVersion: apps/v1
kind: Deployment
metadata:
  name: iioat
  labels:
    name: iioat
spec:
  selector:
    matchLabels:
      name: iioat
  template:
    metadata:
      labels:
        name: iioat
    spec:
      containers:
      - name: iioat-app
        image: IIOS_CONTAINER_REGISTRYignitial/iioat:IIOS_APP_VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: NODE_ENV
            value: "production"
          - name: IIO_SERVER_PORT
            value: "8080"
          - name: IIOS_NAMESPACE
            value: "iioat"
          - name: REDIS_HOST
            value: "redis.default.svc.cluster.local"
          - name: S3_ENDPOINT
            value: "s3.fr-par.scw.cloud"
          - name: S3_BUCKET
            value: "iio1393"
          - name: S3_SECURE
            value: "true"
          - name: S3_REGION
            value: "fr-par"
          - name: EMAILER_SMTP_USER
            value: "support@ignitial.fr"
          - name: EMAILER_SMTP_HOST
            value: "mail.gandi.net"
          - name: EMAILER_SMTP_PORT
            value: "587"
          - name: MONGODB_URI
            value: "iiomc1-hvphm.gcp.mongodb.net"
          - name: MONGODB_USER
            value: "ignitial"
          - name: MONGODB_OPTIONS
            value: "retryWrites=true"
          - name: IIOS_DBNAME
            value: "iioat"
          - name: MONGODB_CONN_MAX_ATTEMPTS
            value: "60"
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: iiosecrets
                key: mongodb_pwd
          - name: S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: iiosecrets
                key: s3_access_key_id
          - name: S3_SECRET_ACESS_KEY
            valueFrom:
              secretKeyRef:
                name: iiosecrets
                key: s3_secret_access_key
          - name: IIOS_EMAILER_SMTP_PASS
            valueFrom:
              secretKeyRef:
                name: iiosecrets
                key: emailer_smtp_pass
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: iioat
spec:
  selector:
    app: iioat
    task: server
  ports:
  - name: http
    port: 80
    targetPort: 8080
