apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`mini.kube`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: iioat
      port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-ingress
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`traefik-ui.kube`)
    kind: Rule
    services:
    - name: traefik-dashboard
      port: 8080
